vars:
  - files:
      train:
        data: data/raw/train.csv
        output_scores: scores.json

stages:
  train:
    cmd: >-
      python -m tblr.bin.train
      --test_size ${train.test_size}
      --const     ${train.const}
      --seed      ${train.seed}
      --data          ${files.train.data}
      --output_scores ${files.train.output_scores}
    deps:
      - ${files.train.data}
    params:
      - train.test_size
      - train.const
      - train.seed
    metrics:
      - ${files.train.output_scores}:
          cache: false
