vars:
  - files:
      train:
        data: data/raw/train.csv
        output_scores: scores.json

stages:
  train:
    cmd: >-
      python tblr/bin/train.py
      --test_size ${train.test_size}
      --seed      ${train.seed}
      --data          ${files.train.data}
      --output_scores ${files.train.output_scores}
    deps:
      - ${files.train.data}
      - tblr
    params:
      - train.test_size
      - train.seed
    metrics:
      - ${files.train.output_scores}:
          cache: false
