name: run
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: pip_install
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: dvc_pull
        run: dvc pull
          python -m tblr.cmd.run
      - name: run
        run: python -m tblr.cmd.run
